spring.application.name=spring-security
server.port=8088

## Datasource
#spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:postgresql://localhost:5432/BANCA_VIRTUAL
spring.datasource.username=BANCA
spring.datasource.password=Fmlr#2701

##JPA
spring.jpa.show-sql=true