spring.application.name=spring-security
server.port=8088

## Datasource
#spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:postgresql://localhost:5432/BANCA_VIRTUAL
spring.datasource.username=BANCA
spring.datasource.password=Fmlr#2701

##JPA
spring.jpa.show-sql=true

## JWT configuration
security.jwt.secret.key=7d0040f7e3ffd8e65ac4e36e9121cab028f246601a3d1b981a2720d051d0dfad
security.jwt.generator.user=AUTH-SPRING-SECURITY